#!/bin/bash
#CUDA_VISIBLE_DEVICES=3 python tune_vtab.py --train-type "prompt" --config-file configs/prompt/cub.yaml MODEL.TYPE "vit" DATA.BATCH_SIZE "4" MODEL.PROMPT.DEEP "False" MODEL.PROMPT.DROPOUT "0.1" MODEL.PROMPT.NUM_TOKENS "50" DATA.FEATURE "sup_vitb16_imagenet21k" DATA.NAME "vtab-oxford_flowers102" DATA.NUMBER_CLASSES "102" DATA.DATAPATH "/home/uit2023/LuuTru/Dungdm/tensorflow_datasets/" MODEL.MODEL_ROOT "/home/uit2023/LuuTru/Dungdm/SWARM_new/vpt-main/checkpoint/" OUTPUT_DIR "/home/uit2023/LuuTru/Dungdm/SWARM_new/vpt-main/work_dir7/"
#CUDA_VISIBLE_DEVICES=3 python tune_vtab.py --train-type "prompt" --config-file configs/prompt/cub.yaml MODEL.TYPE "vit" DATA.BATCH_SIZE "4" MODEL.PROMPT.DEEP "False" MODEL.PROMPT.DROPOUT "0.1" MODEL.PROMPT.NUM_TOKENS "50" DATA.FEATURE "sup_vitb16_imagenet21k" DATA.NAME "vtab-cifar(num_classes=100)" DATA.NUMBER_CLASSES "100" DATA.DATAPATH "/home/uit2023/tensorflow_datasets/" MODEL.MODEL_ROOT "/home/uit2023/LuuTru/Dungdm/SWARM_new/vpt-main/checkpoint/" OUTPUT_DIR "/home/uit2023/LuuTru/Dungdm/SWARM_new/vpt-main/work_dir7/"
#CUDA_VISIBLE_DEVICES=3 python tune_vtab.py --train-type "prompt" --config-file configs/prompt/cub.yaml MODEL.TYPE "vit" DATA.BATCH_SIZE "4" MODEL.PROMPT.DEEP "False" MODEL.PROMPT.DROPOUT "0.1" MODEL.PROMPT.NUM_TOKENS "50" DATA.FEATURE "sup_vitb16_imagenet21k" DATA.NAME "vtab-dmlab" DATA.NUMBER_CLASSES "6" DATA.DATAPATH "/home/uit2023/tensorflow_datasets/" MODEL.MODEL_ROOT "/home/uit2023/LuuTru/Dungdm/SWARM_new/vpt-main/checkpoint/" OUTPUT_DIR "/home/uit2023/LuuTru/Dungdm/SWARM_new/vpt-main/work_dir7/"

CUDA_VISIBLE_DEVICES=3 python tune_vtab.py --train-type "prompt" --config-file configs/prompt/cub.yaml MODEL.TYPE "vit" DATA.BATCH_SIZE "4" MODEL.PROMPT.DEEP "False" MODEL.PROMPT.DROPOUT "0.1" MODEL.PROMPT.NUM_TOKENS "50" DATA.FEATURE "sup_vitb16_imagenet21k" DATA.NAME "vtab-caltech101" DATA.NUMBER_CLASSES "102" DATA.DATAPATH "/home/uit2023/tensorflow_datasets/" MODEL.MODEL_ROOT "/home/uit2023/LuuTru/Dungdm/SWARM_new/vpt-main/checkpoint/" OUTPUT_DIR "/home/uit2023/LuuTru/Dungdm/SWARM_new/vpt-main/work_dir7/"
#CUDA_VISIBLE_DEVICES=3 python tune_vtab.py --train-type "prompt" --config-file configs/prompt/cub.yaml MODEL.TYPE "vit" DATA.BATCH_SIZE "4" MODEL.PROMPT.DEEP "False" MODEL.PROMPT.DROPOUT "0.1" MODEL.PROMPT.NUM_TOKENS "50" DATA.FEATURE "sup_vitb16_imagenet21k" DATA.NAME "vtab-dtd" DATA.NUMBER_CLASSES "47" DATA.DATAPATH "/home/uit2023/tensorflow_datasets/" MODEL.MODEL_ROOT "/home/uit2023/LuuTru/Dungdm/SWARM_new/vpt-main/checkpoint/" OUTPUT_DIR "/home/uit2023/LuuTru/Dungdm/SWARM_new/vpt-main/work_dir7/"
#CUDA_VISIBLE_DEVICES=3 python tune_vtab.py --train-type "prompt" --config-file configs/prompt/cub.yaml MODEL.TYPE "vit" DATA.BATCH_SIZE "4" MODEL.PROMPT.DEEP "False" MODEL.PROMPT.DROPOUT "0.1" MODEL.PROMPT.NUM_TOKENS "50" DATA.FEATURE "sup_vitb16_imagenet21k" DATA.NAME "vtab-oxford_iiit_pet" DATA.NUMBER_CLASSES "37" DATA.DATAPATH "/home/uit2023/tensorflow_datasets/" MODEL.MODEL_ROOT "/home/uit2023/LuuTru/Dungdm/SWARM_new/vpt-main/checkpoint/" OUTPUT_DIR "/home/uit2023/LuuTru/Dungdm/SWARM_new/vpt-main/work_dir7/"
#CUDA_VISIBLE_DEVICES=3 python tune_vtab.py --train-type "prompt" --config-file configs/prompt/cub.yaml MODEL.TYPE "vit" DATA.BATCH_SIZE "4" MODEL.PROMPT.DEEP "False" MODEL.PROMPT.DROPOUT "0.1" MODEL.PROMPT.NUM_TOKENS "50" DATA.FEATURE "sup_vitb16_imagenet21k" DATA.NAME "vtab-svhn" DATA.NUMBER_CLASSES "10" DATA.DATAPATH "/home/uit2023/tensorflow_datasets/" MODEL.MODEL_ROOT "/home/uit2023/LuuTru/Dungdm/SWARM_new/vpt-main/checkpoint/" OUTPUT_DIR "/home/uit2023/LuuTru/Dungdm/SWARM_new/vpt-main/work_dir7/"
#CUDA_VISIBLE_DEVICES=3 python tune_vtab.py --train-type "prompt" --config-file configs/prompt/cub.yaml MODEL.TYPE "vit" DATA.BATCH_SIZE "4" MODEL.PROMPT.DEEP "False" MODEL.PROMPT.DROPOUT "0.1" MODEL.PROMPT.NUM_TOKENS "50" DATA.FEATURE "sup_vitb16_imagenet21k" DATA.NAME "vtab-eurosat" DATA.NUMBER_CLASSES "10" DATA.DATAPATH "/home/uit2023/tensorflow_datasets/" MODEL.MODEL_ROOT "/home/uit2023/LuuTru/Dungdm/SWARM_new/vpt-main/checkpoint/" OUTPUT_DIR "/home/uit2023/LuuTru/Dungdm/SWARM_new/vpt-main/work_dir7/"

